spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    username: minhnhut
    password: 1
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydb
  application:
    name: HoMinhNhut




mail:
  host: smtp.gmail.com
  port: 587
  username: nhuthmps32162@fpt.edu.vn
  password: nqxr jgzr dymp upio
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

server:
  port: 1311
  servlet:
    context-path: /mnw

asm:
  key: c29tZSByYW5kb20gc3RyaW5nIGVuY29kZWQgaW4gQmFzZTY0
